# Server Configuration
server:
    port: 8080
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   uri: ${MONGO_DB_URI}
  # uri: mongodb://beatlm:beatlm@ds123029.mlab.com:23029/tmrecipes
   database: tmrecipes
   
 
 management:
  endpoints:
   web:
    cors:
     allowed-origins: '*'

   
