# Server Configuration
server:
    port: 8080
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   uri: ${MONGO_DB_URI}
   database: ${MONGO_DB_NAME}
   host: ${MONGO_DB_HOST}
   port: ${MONGO_DB_PORT}
   user: ${MONGO_DB_USER}
   pass: ${MONGO_DB_PASS}
   
 
 management:
  endpoints:
   web:
    cors:
     allowed-origins: '*'

   
